name: Build

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ID: ${{ github.run_number }}
    steps:
      - name: Clone project
        uses: actions/checkout@v7

      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run build with Gradle Wrapper
        run: chmod +x ./gradlew && ./gradlew clean build --refresh-dependencies

      - name: Get project version
        id: get_version
        run: |
          VERSION=$(./gradlew -q printVersion)
          echo "version=${VERSION##$'\n'}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}-build.${{ github.run_number }}
          name: '${{ steps.get_version.outputs.version }}'
          generate_release_notes: true
          body: |
            # ❓ What file to choose?
            1.16.* or 1.17.* — DeluxeMenus-Modern-1_16.jar
            1.18.* or newer  — DeluxeMenus-Modern-1_18.jar
          files: |
            distribution-1_16/build/libs/DeluxeMenus-Modern-1_16.jar
            distribution-1_18/build/libs/DeluxeMenus-Modern-1_18.jar
